const Api = [
  {
    title: "MITACS Globalink, for research positions in Canada.",
    desc: "",
    url: "https://www.mitacs.ca/en/programs/globalink/globalink-research-internship",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "LPI Summer Intern Program in Planetary Science, for both national and international students.",
    desc: "",
    url: "https://www.lpi.usra.edu/lpiintern/application/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "NASA - CalTech Summer Undergraduate Research Fellowship (SURF), for research positions at Jet Propulsion Laboratory, California Institute of Technology.",
    desc: "",
    url: "https://www.jpl.nasa.gov/edu/intern/apply/caltech-summer-undergraduate-research-fellowship/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Santa Fe Institute Summer Research Experience",
    desc: "",
    url: "https://www.santafe.edu/engage/learn/programs/undergraduate-complexity-research",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Robotics Institute for Summer Scholars, CMU",
    desc: "",
    url: "https://riss.ri.cmu.edu/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Data Science for Social Good Fellowship, CMU",
    desc: "",
    url: "https://www.dssgfellowship.org/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "QRLSSP Summer Program, Arizona State University: Only for US Citizens / Permanent Residents",
    desc: "",
    url: "https://qrlssp.asu.edu/summerprogram",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Summer Undergraduate Research fellowship program, Rockfeller Institute",
    desc: "",
    url: "https://www.rockefeller.edu/education-and-training/surf/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "CalTech SURF Program",
    desc: "",
    url: "https://sfp.caltech.edu/undergraduate-research/programs/surf/application_information",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Space Astronomy Summer Program, Space Telescope Science Institute (STScI)",
    desc: "",
    url: "http://www.stsci.edu/opportunities/space-astronomy-summer-program",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Data Visualization Programming Summer Student Internship in New York City, Flatiron Institute. (NEW LINK NEEDED)",
    desc: "",
    url: "https://simonsfoundation.wd1.myworkdayjobs.com/en-US/simonsfoundationcareers/job/162-Fifth-Avenue/Data-Visualization-Intern--SCC_R0000579",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Summer Research Program, Princeton University",
    desc: "",
    url: "https://undergraduateresearch.princeton.edu/programs/summer-programs?field_princeton_status_eligibili_value=Non-Princeton+undergrads&field_class_year_eligibility_value=Juniors&field_division_value=Engineering",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "International Student Research Internship Program - McKelvey School of Engineering",
    desc: "",
    url: "https://engineering.wustl.edu/academics/undergraduate-research/international-student-research-internship-program.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Luddy School of Informatics, Computing, and Engineering - Global Talent Attraction Program (GTAP)",
    desc: "",
    url: "https://luddy.indiana.edu/research/student-research/fellowship.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "BioChemCoRe (Biology and Chemistry Computational Research), Amaro Lab, UC San Diego",
    desc: "",
    url: "https://biochemcore.ucsd.edu/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Global Research Experience in Advanced Technologies (GREAT) Program, UC Davis",
    desc: "",
    url: "https://great.ucdavis.edu/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "ICT Summer Research Program",
    desc: "",
    url: "https://ict.usc.edu/academics/internships/application/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "UC Berkeley Amgen Scholars program",
    desc: "",
    url: "https://amgenscholars.berkeley.edu/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Summer Undergraduate Program in Engineering Research at Berkeley (SUPERB) (for Information Technology students",
    desc: "",
    url: "https://eecs.berkeley.edu/resources/undergrads/research/superb",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "SUMMER RESEARCH OPPORTUNITIES PROGRAM(SROP), Purdue University",
    desc: "",
    url: "https://www.purdue.edu/gradschool/diversity/programs/summer-research-opportunities-program/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Summer Undergraduate Research Fellowship (SURF), Stanford University",
    desc: "",
    url: "https://engineering.stanford.edu/students-academics/equity-and-inclusion-initiatives/prospective-graduate-programs/summer",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "IPAM UCLA Program",
    desc: "",
    url: "http://www.ipam.ucla.edu/programs/student-research-programs/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Research fellowship at ETH Zurich",
    desc: "",
    url: "https://www.inf.ethz.ch/studies/summer-research-fellowship.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "CERN Summer Student Program",
    desc: "",
    url: "https://careers.cern/summer",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "CERN OpenLab for Computer Science Undergraduates",
    desc: "",
    url: "https://openlab.cern/education",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "E3, EPFL (Switzerland)",
    desc: "",
    url: "https://eee.epfl.ch/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Summer at EPFL",
    desc: "",
    url: "https://summer.epfl.ch/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Swissnex Program",
    desc: "",
    url: "https://swissnex.org/india/thinkswiss/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Max Planck Institute for Gravitational Physics, for all students.",
    desc: "",
    url: "https://www.aei.mpg.de/student-internships",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Max Planck Institute for Software Systems",
    desc: "",
    url: "https://apply.mpi-sws.org/register/internship/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Warwick Statistics Internship Scheme, University of Warwick",
    desc: "",
    url: "https://warwick.ac.uk/fac/sci/statistics/research/internships/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "DAAD WISE Scholarship",
    desc: "",
    url: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50015295",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "HZDR Dresden, Summer student program (Germany)",
    desc: "",
    url: "https://www.hzdr.de/db/Cms?pOid=34387&pNid=2519",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "MaxSIP (Max Planck Institute Summer Internship)",
    desc: "",
    url: "https://imprs-ls.opencampus.net/en/maxsip_application_info",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "UROP International, RWTH Aachen",
    desc: "",
    url: "http://www.rwth-aachen.de/cms/root/Forschung/Angebote-fuer-Forschende/Angebote-fuer-Studierende/UROP/UROP-INternational/~wnr/Informationen-fuer-Studierende/?lidx=1",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "DSSGx UK Summer Fellowship, University of Warwick",
    desc: "",
    url: "https://warwick.ac.uk/research/data-science/warwick-data/dssgx/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Visual Geometry Group",
    desc: "",
    url: "https://www.robots.ox.ac.uk/~vgg/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "ICTS LONG TERM VISITING STUDENTS PROGRAM for both International and Indian Students. Aims to provide opportunities to students of science, mathematics and engineering to spend a longer period of time (1 or 2 semesters).",
    desc: "",
    url: "https://www.icts.res.in/academic/long-term-visiting-student-program",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "ICTS SN BHATT Memorial Excellence Fellowship for Undergraduate students of science, mathematics and engineering, who are in their third, fourth or fifth year of the program are eligible to apply.",
    desc: "",
    url: "https://www.icts.res.in/academic/summer-research-program",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "SPIKE @ UNIST, Summer Program for Internship and Korean Experience",
    desc: "",
    url: "https://spike.unist.ac.kr:10449/02_learn/learn03.php",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "SPIKE@UNIST (South Korea)",
    desc: "",
    url: "https://spike.unist.ac.kr:10449/02_learn/learn03.php",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "GIST Global Internship Program (South Korea)",
    desc: "",
    url: "https://www.gist.ac.kr/en/html/sub07/0702.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Research internship @ Yonsei University",
    desc: "",
    url: "https://summer.yonsei.ac.kr/home/program/internship02.asp",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Yonsei University",
    desc: "",
    url: "https://summer.yonsei.ac.kr/home/program/internship02.asp",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "NTHU Summer Internship Program",
    desc: "",
    url: "http://eng-en.web.nthu.edu.tw/files/14-1130-129169,r1447-1.php",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "TIGP-IIP, Academia Sincia, Taiwan",
    desc: "",
    url: "https://tigpsip.apps.sinica.edu.tw/index.php",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "ITRI Global Internship program",
    desc: "",
    url: "https://www.itri.org.tw/english/ListStyle.aspx?DisplayStyle=05&SiteID=1&MmmID=617731531432246346",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "TEEP@Asia (Taiwan)",
    desc: "",
    url: "https://teep.studyintaiwan.org/programs/Engineering",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "TEEP Internship, Taiwan",
    desc: "",
    url: "https://www.roc-taiwan.org/in_en/post/2749.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "University of Tokyo, Amgen Scholarship Japan (only Bio Tech and Bio-Chem Programs)",
    desc: "",
    url: "http://www.amgenscholars.com/japan-program",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "OIST Research Internship Program, Okinawa Institute of Science and Technology",
    desc: "",
    url: "https://admissions.oist.jp/oist-research-internship-program-description",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "NIMS (Japan)",
    desc: "",
    url: "https://www.nims.go.jp/eng/hr-development/internship.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Hennge Global Internship Program, for remote internship in a Japan-based tech start-up.",
    desc: "",
    url: "https://hennge.com/global/gip.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "ISternship Summer Student Program, IST Austria",
    desc: "",
    url: "https://phd.pages.ist.ac.at/isternship/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "IVISP, HKUST (only for senior year undergraduates + postgraduates)",
    desc: "",
    url: "https://pg.ust.hk/ivisp",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "SURP, CUHK",
    desc: "",
    url: "http://www.summer.cuhk.edu.hk/surp/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "SURP (Hongkong)",
    desc: "",
    url: "http://www.summer.cuhk.edu.hk/surp/?fbclid=IwAR0-H6g4x7UetRxFQkcnK95zvgjkp81TjgCZlBgv-NjrRSxWiOxy84TZuhw",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "UNSW Civil and Environmental Engineering Research Internship",
    desc: "",
    url: "https://www.engineering.unsw.edu.au/civil-engineering/study-with-us/international-exchange/research-internship-to-unsw-for-international-students",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "UNSW Research Internship (Australia)",
    desc: "",
    url: "https://www.unsw.edu.au/science/student-life-resources/student-opportunities/research-integrated-learning",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Summer Intern at the Kupcinet Getz International Summer Science School of the Weizmann Institute of Science",
    desc: "",
    url: "https://www.weizmann.ac.il/feinberg/admissions/kupcinet-getz-international-summer-school/about-program-0",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Summer Training Program,CNIO",
    desc: "",
    url: "https://www.cnio.es/en/education-and-career-development/career-development-programmes/undergraduate-students/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "OECD Internship Programme (France)",
    desc: "",
    url: "https://www.oecd.org/careers/internship-programme/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "KAUST (Saudi Arabia)",
    desc: "",
    url: "https://vsrp.kaust.edu.sa/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "HSE University, Moscow Computer Science Internships",
    desc: "",
    url: "https://cs.hse.ru/en/internships/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "IPAM UCLA, RIPS Program",
    desc: "",
    url: "http://www.ipam.ucla.edu/programs/student-research-programs/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Amgen Scholars Program",
    desc: "",
    url: "https://amgenscholars.com/",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "UX Research Internship, Red Hat",
    desc: "",
    url: "https://us-redhat.icims.com/jobs/83084/remote-us-nc/job",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Allen Institute for AI, Research and Engineering Internships",
    desc: "",
    url: "https://allenai.org/internships",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "ICTS Summer research program, by ICTS-TIFR.",
    desc: "",
    url: "https://www.icts.res.in/academic/summer-research-program",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "DAAD Wise Scholarship, for research positions in Germany",
    desc: "",
    url: "https://www.daad.de/go/en/stipa50015295",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title:
      "Shastri Research Student Fellowship by Shastri Indo-Canadian Institute",
    desc: "",
    url: "https://www.shastriinstitute.org/shastri-research-student-fellowship",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Viterbi India Program, sponsored by IUSSTF and USC Viterbi",
    desc: "",
    url: "https://www.iusstf.org/program/iusstf-viterbi-program",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Khorana Program for Scholars, sponsored by IUSSTF",
    desc: "",
    url: "https://www.iusstf.org/program/khorana-program-for-scholars",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Charpak Global Scholarship, funded by French Embassy in India",
    desc: "",
    url: "https://www.inde.campusfrance.org/charpak-lab-scholarship",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "Indian Student Internship Program at NTHU",
    desc: "",
    url: "http://oga.nthu.edu.tw/news.php?id=233&lang=en",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "IBM Blue Mix Research Internship",
    desc: "",
    url: "https://researcher.watson.ibm.com/researcher/view_group_subpage.php?id=8101",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
  {
    title: "IBM Extreme Blue (limited to IITs and NITs)",
    desc: "",
    url: "http://www-07.ibm.com/employment/in/students/extreme-blue/index.html",
    roles: "Research Intern",
    stipend: "Data Unavailable",
  },
];

export default Api;
